name: BakingLog
options:
  bundleIdPrefix: com.bakinglog
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

settings:
  SWIFT_VERSION: "5.9"
  DEVELOPMENT_TEAM: "" # Set your team ID here

targets:
  BakingLog:
    type: application
    platform: iOS
    sources:
      - BakingLog
    settings:
      INFOPLIST_FILE: BakingLog/Resources/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.bakinglog.app
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: 1
    dependencies:
      - target: BakingLogWidgetExtension
    postCompileScripts: []

  BakingLogWidgetExtension:
    type: app-extension
    platform: iOS
    sources:
      - BakingLogWidget
      - path: BakingLog/Models
        group: Shared/Models
      - path: BakingLog/Services/APIClient.swift
        group: Shared/Services
    settings:
      INFOPLIST_FILE: BakingLogWidget/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.bakinglog.app.widget
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: 1
      ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
