name: BakingLog
options:
  bundleIdPrefix: com.bakinglog
  deploymentTarget:
    iOS: "17.0"

settings:
  SWIFT_VERSION: "6.0"
  DEVELOPMENT_TEAM: "" # Set your team ID here

targets:
  BakingLog:
    type: application
    platform: iOS
    sources:
      - BakingLog
    settings:
      INFOPLIST_FILE: BakingLog/Resources/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.bakinglog.app
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: 1
      CODE_SIGN_ENTITLEMENTS: BakingLog/Resources/BakingLog.entitlements
    dependencies:
      - target: BakingLogWidgetExtension

  BakingLogWidgetExtension:
    type: app-extension
    platform: iOS
    sources:
      - BakingLogWidget
      - path: BakingLog/Models
        group: Shared/Models
      - path: BakingLog/Services/APIClient.swift
        group: Shared/Services
      - path: BakingLog/App/AppGroup.swift
        group: Shared/App
    settings:
      INFOPLIST_FILE: BakingLogWidget/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.bakinglog.app.widget
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: 1
      CODE_SIGN_ENTITLEMENTS: BakingLogWidget/BakingLogWidget.entitlements
