name: BakingLog
options:
  bundleIdPrefix: com.bakinglog
  deploymentTarget:
    iOS: "17.0"

settings:
  SWIFT_VERSION: "6.0"
  DEVELOPMENT_TEAM: TX552W76H7

targets:
  BakingLog:
    type: application
    platform: iOS
    sources:
      - BakingLog
    settings:
      INFOPLIST_FILE: BakingLog/Resources/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.bakinglog.app
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: 1
      CODE_SIGN_ENTITLEMENTS: BakingLog/Resources/BakingLog.entitlements
